name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.1
          elixir-version: 1.11.2

      - name: Check mix format
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: |
          mix deps.get
          mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 23.0
            elixir: 1.11.2
          - erlang: 23.0
            elixir: 1.10.4
          - erlang: 22.1
            elixir: 1.9.4
          - erlang: 22.1
            elixir: 1.8.2
          - erlang: 21.3
            elixir: 1.7.4
          - erlang: 20.3
            elixir: 1.6.6
          - erlang: 20.3
            elixir: 1.5.3
          - erlang: 19.3
            elixir: 1.4.5
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}

      - name: Run tests
        run: |
          mix compile --no-deps-check
          mix test --no-deps-check --trace
