name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
          elixir-version: 1.14.3

      - name: Publish
        run: |
          mix deps.get
          mix compile
          .github/workflows/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
