name: Publish

on:
  push:
    branches:
      - main

jobs:
  outdated:
    name: Check outdated
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.2
          elixir-version: 1.14.3

      - name: Publish
        run: |
          mix deps.get
          mix compile
          .github/workflows/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
